Run using ``ipython3 nbconvert --to slides --post serve basic-numpy.ipynb`` (Now using livereveal)

In [1]:
%matplotlib nbagg

# For easier python 2 compatibility:
from __future__ import division, print_function, absolute_import

# Normal imports:
import numpy as np

In [2]:
import numpy as np

# Keep the random numbers identical over runs
np.random.seed(12345)

# Introduction to the scientific python stack

![](images/python-stack.svg)


In this course we will cover:

* Numpy basics
* Matplotlib
* Less basic Numpy - 14.11
* image processing - 29.11

# Basics Numpy

About Numpy
===========


![](../images/python-stack.svg)

  * Basis for scientific computing with Python
  * A powerfull N-dimension array object
  * Basic and not so basic math operations
  * Linear algebra operations
  * _Normally_ homogenous data (i.e. numbers)
  * random numbers, FFT, sorting, …

Convention
----------

In [2]:
import numpy as np

# Numpy is useful

* Homogenous data:
  - Experimental data sets
  - Simulations
  - …

   **For example**:

In [114]:
x = np.linspace(0, 9, 1001)
print(x[::200])

[ 0.   1.8  3.6  5.4  7.2  9. ]


In [115]:
print(np.sqrt(x)[::200])

[ 0.          1.34164079  1.8973666   2.32379001  2.68328157  3.        ]


NumPy can be much faster (typically $\approx 50\times$):

In [116]:
%%timeit
numpy_result = np.sqrt(x)

The slowest run took 12.47 times longer than the fastest. This could mean that an intermediate result is being cached.
100000 loops, best of 3: 2.87 µs per loop


In [111]:
from math import sqrt
x = list(x)

In [112]:
%%timeit
python_result = [sqrt(value) for value in x]

10000 loops, best of 3: 80.6 µs per loop


(The actual speedup depends, but it can be much more for simple operations like $\times, +$)

# Arrays are 


A homogeneous N-Dimensional (``ndarray``)
* dimensions are called axes
* number of axes, or dimensions, is the rank


For example:

The coordinates of a point in a 3D space `[2, 1, 3]` is an array of rank 1, because it has one axis with length 3

The array

```python
[[ 1., 0., 0.],
 [ 0., 1., 2.]]
 ```
 
 * has rank 2 (2-dimensions)
 * the first dimension (axis) has length 2
 * the second 3
 

Some important **attributes** of an **ndarray** object are:

`ndarray.ndim`   
 number of axes (dimensions) of the array, referred to as rank
   
`ndarray.shape`    
size of the array in each dimension

`ndarray.size`   
number of elements of the array

`ndarray.dtype`   
type of the elements in the array

## Array creation

In [28]:
np.array([2,3,4])

array([2, 3, 4])

### Arrays can have different ranks (number of dimensions) 

A bit like nested lists:


**0 dimensional**

In [7]:
arr = np.array(5)
# although 0-d arrays are sometimes a bit special :(
print(arr)
print('The rank is:', arr.ndim)
print('The shape is:', arr.shape)

5
The rank is: 0
The shape is: ()


**1 dimensional**

In [5]:
arr = np.array([4, 5, 6])
print(arr)
print('The rank is:', arr.ndim)
print('The shape is:', arr.shape)

[4 5 6]
The rank is: 1
The shape is: (3,)


**2 dimensional**

In [ ]:
arr = np.array([[1, 2],
                [3, 4],
                [5, 6]])
print(arr)
print('The dimension is:', arr.ndim)
print('The shape is:', arr.shape)

**3 dimensional**

In [ ]:
arr = np.array([[[1, 2],
                 [2, 3]],
                [[4, 5],
                 [8, 9]]])
print('The dimension is:', arr.ndim)
print('The shape is:', arr.shape)

... and in general n-dimensional, they are called **`ndarray`** after all

### Functions for generating arrays

In [26]:
arr = np.zeros((3, 4))
print(repr(arr))
print('Shape:', arr.shape)

array([[ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])
Shape: (3, 4)


In [27]:
np.zeros(3, dtype=np.int64)

array([0, 0, 0])

In [15]:
np.full((1,3), 5)

array([[ 5.,  5.,  5.]])

#### Special one dimensional arrays

Ranges for float and integer arrays

In [30]:
np.arange(10)  # much like pythons range

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

<font color='red'>Note:</font> Please do not use ``arange`` for floats!

In [16]:
np.linspace(0, 3, 7)

array([ 0. ,  0.5,  1. ,  1.5,  2. ,  2.5,  3. ])

** N-Dimensional versions:**

```np.meshgrid; np.ogrid; np.mgrid```

#### See also:
```python
array, zeros, zeros_like, ones, ones_like, empty, empty_like, arange, 
linspace, numpy.random.rand, numpy.random.randn, fromfunction, fromfile,
full, loadtxt, eye, diag
```

#### Exercise

1. Use ```np.random.randint``` to create a 2 x 2 matrix. 

2. Create again this matrix typing each element.

<!---
a = np.random.randint(2,6, (2,2))
--->

**Solution:**

# Lets do math!

In [54]:
## scalar addition
arr = np.linspace(-1, 1, 5)
print(arr, " + 1 = ")
#arr + 1

[-1.  -0.5  0.   0.5  1. ]  + 1 = 


array([ 0. ,  0.5,  1. ,  1.5,  2. ])

In [65]:
## vector sum
a = np.arange(4).reshape(2,2)
b = -np.arange(4).reshape(2,2)
print('a \n', a, '\nb\n', b)
#print('a + b = \n', a+b)

a 
 [[0 1]
 [2 3]] 
b
 [[ 0 -1]
 [-2 -3]]


array([[ -2,  -3],
       [ -6, -11]])

### Elementwise operations (unlike lists)

A new array is created and filled with the result.

#### Arithmetic operators

```python
    a-b

    b**2

    a < 35

    A*B  # elementwise product

    A.dot(B)  # matrix product
    
```

Some operations, such as += and *=, act in place, modify an existing array rather than create a new one. 

```python
    a *= 3
```

#### Universal Functions (ufunc)

```python
    np.exp()

    np.sqrt()
    
    np.sin()

```
    

## Indexing, Slicing and Iterating

Like lists
```python
arr[]
arr[:]
arr[::]
```

In [127]:
a = np.arange(5)**2
a

array([ 0,  1,  4,  9, 16])

In [128]:
# get an element
a[-1]

16

In [129]:
# use indexing to assign new values to the array
a[0] = 100
a

array([100,   1,   4,   9,  16])

In [132]:
a[::2]

array([100,   4,  16])

In [104]:
for element in a:
    print(element)

100
1
4
9
16


# Conclusions

We have seen:


1. How to do convenient, fast math in NumPy
2. ndarray
	* its attributes
    * how to create them
    * operations, slicing and indexing
3. Later more information on how to plot with matplotlib


# References

* https://docs.scipy.org/doc/numpy-dev/user/quickstart.html